Piper/Alexandra/urls.py
from django.conf.urls import patterns , include, url
from django.conf import settings
from django.conf.urls.static import static
from Alexandra import views
from Alexandra.api import PostResource, UserResource
from django.views.decorators.cache import cache_page


post_resource = PostResource()
user_resource = UserResource()

urlpatterns = patterns ( '',
# url(r'^$', views.posts, name = 'index' ),
url(r'^$', views.posts, name = 'posts'),
url(r'^post/(?P<post_id>\d+)', views.post, name = 'post'),
url(r'^new_post/', views.new_post, name = 'new_post'),
url(r'^api/posts/', include(post_resource.urls)),
url(r'^api/users/', include(user_resource.urls)),
(r'^accounts/', include('registration.backends.default.urls'))
# url(r'^api/posts/doc/', include('tastypie_swagger.urls', namespace='post_tastypie_swagger'),
# kwargs={"tastypie_api_module":"Alexandra.registration.posts", "namespace":"post_tastypie_swagger"}
# ),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Piper/Project_120/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Project_120.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('Alexandra.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

Piper/Alexandra/models.py
from django.db import models
from django.forms import ModelForm, Textarea, FileInput
from django.utils.translation import ugettext_lazy as _
from django.contrib.admin import widgets
import datetime
from django.utils import timezone



class User(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length = 20)
    password = models.CharField(max_length = 20)
    email = models.CharField(max_length = 254)
#    birthday = models.IntegerField(8)
    GENDER_REGISTRATION = (
      ('M', 'Male'),
      ('F', 'Female'),
      ('O', 'Other'),
    )
    gender = models.CharField(max_length = 1, choices = GENDER_REGISTRATION, default = 'O')
    created_at = models.DateTimeField(editable=False, default=timezone.now)
    last_modified = models.DateTimeField(default=timezone.now)
    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = datetime.datetime.today()
        self.last_modified = datetime.datetime.today()
        return super(User, self).save(*args, **kwargs)

   

class Post (models.Model):
    id = models.AutoField(primary_key=True)
    text_content = models.CharField(max_length = 200)
# for the mvp, perhaps just store a link instead of an s3 key
    image = models.ImageField(upload_to='Alexandra', default='NULL')
    created_at = models.DateTimeField(editable=False, default=timezone.now)
    last_modified = models.DateTimeField(default=timezone.now)
    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = datetime.datetime.today()
        self.last_modified = datetime.datetime.today()
        return super(Post, self).save(*args, **kwargs)
    class Meta:
        get_latest_by = 'last_modified'
        ordering = ['-last_modified']

class PostForm (ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'text_content']
        labels = {
            'text_content': _('Description'),
            'image': _('Image'),
        }
        error_messages = {
            'text_content': {
                'max_length': _('Character limit is 200 characters'),
            },
        }
        widgets = {
            'text_content': Textarea(attrs={'cols': 50, 'rows': 5}),
            'image': FileInput(),
        }

#class Comment (models.Model):
#    id = models.AutoField(primary_key=True)
#    username = models.CharField(max_length = 60)
#    content = models.CharField(max_length = 1024)
#    timestamp = models.DateTimeField('Posted: ')
    
#class User_post(models.Model):
#    user = models.ForeignKey(User)
#    post = models.ForeignKey(Post)
    
#class Posts_comments (models.Model):
#    post = models.ForeignKey(Post)
#    comment = models.ForeignKey(Comment)
    
  

Piper/Alexandra/forms.py
from django import forms

class DocumentForm(forms.Form):
        docfile = forms.FileField(
                label='Select a file'
        )

Piper/Alexandra/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.core import serializers
from django import forms
from django.template import RequestContext
#from .models import User 
from .models import Post
from .models import PostForm
from django.core.cache import cache
import cPickle as pickle


# from .models import Document
# from .forms import DocumentForm
def index(request):
#    user = User.objects.all()
    #names = ",".join(map(lamda x:x.username, user))
#    data = serializers.serialize('json', user)
#    return HttpResponse(data)
    return HttpResponse('test')


def posts(request):
    latest_posts = Post.objects.order_by('-created_at')[:10]
    context = {'latest_posts' : latest_posts, 'form':PostForm()}

    return render(request, 'Alexandra/index.html', context)


def post(request, post_id):
    if not Post.objects.filter(id=post_id):
        return HttpResponse('Bad post id')
    thispost = Post.objects.get(id=post_id)
    return render(request, 'Alexandra/single_post.html', {'post': thispost})


def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(commit=True)
            return posts(request)
        else:
            print form.errors
    else:
         form = PostForm()
    return render(request, 'Alexandra/new_post.html', {'form': form})
#

def set_cache(request):

    latest_view = Post.objects.order_by('-created_at')[:10]
    context = {'latest_posts' : latest_view, 'form':PostForm()}

    in_cache = cache.get('latest_view')

    if in_cache:
      return render(request, 'Alexandra/index.html', in_cache)
    else:
      cache.set('latest_view', cPickle.dump(context, 60*15))

    return HttpResponse(message)

# Create your views here.

Piper/Alexandra/templates/Alexandra/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Piper</title>
    <meta name="description" content="the social network">
    <meta name=viewport content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">

    <link rel="stylesheet" href="{% static 'Alexandra/Semantic/semantic.min2.css' %}">
    <link rel="stylesheet" href="{% static 'Alexandra/piper.css' %}"/>
</head>

<body>
    <div id="header">
    {% block header %}
    <a href="{% url 'posts' %}">Home</a> | 

    {% if user.is_authenticated %}
        Logged In: {{ user.username }} 
        (<a href="{% url 'auth_logout' %}">Log out</a> | 
        <a href="{% url 'auth_password_change' %}">Change Password </a>)
    {% else %}
       <a href="{% url 'auth_login' %}">Login</a>
    {% endif %}
    <hr />
    {% endblock %}
    </div>

    <div id="content">
    {% block content %}{% endblock %}
    </div>

    <div id="footer">
    {% block footer %}
        <hr />
    {% endblock %}
    </div>
</body>

Piper/Alexandra/templates/Alexandra/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html manifest="{% static 'Alexandra/piper.appcache' %}">
<head>
    <meta charset="utf-8">
    <title>Piper</title>
    <meta name="description" content="the social network">
    <meta name=viewport content="width=device-width, initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">

    <link rel="stylesheet" href="{% static 'Alexandra/Semantic/semantic.min2.css' %}">
    <link rel="stylesheet" href="{% static 'Alexandra/piper.css' %}">
</head>

<body>
    <div class="ui grid">
        <div class="one wide row"></div>
        <div class="one wide row"></div>
        <h1 class="ui center aligned header title-text">
            <!--use the user's first name here-->Alexandra<!---->'s Piper
        </h1>
    </div>
    <div class="ui visible inverted labeled icon top sidebar menu navbar-elem">
        <a href="#" class="item">
            <i class="home icon"></i>
            Home
        </a>
        <a id="newpostbutton" class="item">
            <i class="comment outline icon"></i>
            New Post
        </a>
    </div>

    <div class="ui center aligned grid site-bg">
        <!--
        <div class="two wide column"></div>
        <div class="three wide column">
            <div class="ui card">
                <div class="image">
                    <img src="" alt="profile picture"/>
                </div>
                <div class="content">
                    <a class="header">Name</a>
                    <div class="description">
                        Some status
                    </div>
                    <div class="extra content">
                        <div class="ui feed">
                            <div class="event">
                                <div class="label">
                                    <img src="" alt="thumbnail"/>
                                </div>
                                <div class="content">
                                    <div class="summary">
                                        <a href="#" class="user">
                                            Some user
                                        </a> did something
                                    </div>
                                </div>
                            </div>
 
                            <div class="event">
                                <div class="label">
                                    <img src="" alt="thumbnail"/>
                                </div>
                                <div class="content">
                                    <div class="summary">
                                        <a href="#" class="user">
                                            Some user
                                        </a> did something
                                    </div>
                                </div>
                            </div>
 
                            <div class="event">
                                <div class="label">
                                    <img src="" alt="thumbnail"/>
                                </div>
                                <div class="content">
                                    <div class="summary">
                                        <a href="#" class="user">
                                            Some user
                                        </a> did something
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        -->

        <!-- Vertical scrolling -->
        <div id="postsscroll" class="ten wide column">
            <div id="postlist" class="ui segment">
{% for post in latest_posts %}
            <!--<div class="ui vertical segment">
                <div class="content">
{% if post.image %}
                    <a href="javascript:void(0);" onclick="LoadSinglePost({{post.id}});return false;"><img id="postimage{{post.id}}" class="ui image center" src='{{ post.image.url }}' alt='user image'/></a>
{% endif %}
                    <p id="posttext{{post.id}}">{{post.text_content}}</p>
                    <div class="left aligned column">
                    <div class="ui comments">
                        <h3 class="ui dividing header">Comments</h3>
                        <div class="comment">
                            <a class="avatar">
                                <img src="">
                            </a>
                            <div class="content">
                                <a class="author">User1</a>
                                <div class="metadata">
                                    <span class="date">Today at 5:42PM</span>
                                </div>
                                <div class="text">
                                    the comment.
                                </div>
                            </div>
                        </div>
                        <form class="ui reply form">
                            <div class="field">
                                <input type="text"></input>
                            </div>
                            <div class="ui blue labeled submit icon button">
                                <i class="icon edit"></i>Comment
                            </div>
                        </form>
                    </div>
                    </div>
                </div>
            </div>-->
{% endfor %}
            </div>
        </div>
        <!-- /Vertical scrolling -->


        <!--<div class="three wide column"></div>-->
    </div>

    <div id="newpostmodal" class="ui modal">
        <i class="close icon"></i>
        <div class="header">
            New Post
        </div>
        <div class="content">
            <div class="ui form segment">
            <form id='new_post_form' method='post' enctype= "multipart/form-data" action='/new_post/'>
            {% csrf_token %}
            <div class="field">
                <label>
                Image
                </label>
                <input id="id_image" name="image" type="file" />
                <div id="id_image_styled" class="ui submit button">
                <div>Upload an image</div>
                </div>
            </div>
            <div class="field">
                <label>
                Description
                </label>
                <textarea cols="50" id="id_text_content" maxlength="200" name="text_content" rows="5"></textarea>
            </div>
            <br/>
            <input id="new_post_submit" class="ui positive right labeled button" type='submit' name='submit' value='Submit' />
            </form>
            </div>
 
        </div>
        <div class="actions">
            <div id="new_post_submit_styled" class="ui positive right labeled button">
                Submit
            </div>
        </div>
    </div>

    <div id="singlepostmodal" class="ui basic long modal">
        <i class="white close icon"></i>
        <div class="content">
            <div class="description">
                <h3 id="singlepostdescription"></h3>
            </div>
        </div>
        <div class="content">
            <div class="ui large image">
                <img id="singlepostimage" src='{{ post.image.url }}' alt='user image'/></a>
            </div>
        </div>
<!--        <div class="content">
            <div class="ui comments">
                <div class="ui segment">
                    <h3 class="ui dividing header">Comments</h3>
                    <div class="comment">
                        <a class="avatar">
                            <img src="">
                        </a>
                        <div class="content">
                            <a class="author">User1</a>
                            <div class="metadata">
                                <span class="date">Today at 5:42PM</span>
                            </div>
                            <div class="text">
                                the comment.
                            </div>
                        </div>
                    </div>
                </div>
                <form class="ui reply form">
                    <div class="field">
                        <input type="text"></input>
                    </div>
                    <div class="ui blue labeled submit icon button">
                        <i class="icon edit"></i>Comment
                    </div>
                </form>
            </div> 
        </div>-->
    </div>

    <div class="main footer">
        <div class="ui divider"></div>
        <div class="ui center aligned grid">
            <div class="column">
                <div class="ui divided horizontal footer link list">
                    <div class="item">
                        Piper
                    </div>
                    <div class="item">
                        <a href="{% static 'Alexandra/Leg5APIDoc.pdf' %}">API Documentation</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'Alexandra/Semantic/semantic.js' %}"></script>
    <script type="text/javascript" src="{% static 'Alexandra/piper.js' %}"></script>
</body>
</html>

Piper/Alexandra/templates/Alexandra/indexbootstrap.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Alexandra's social network</title>
        <link rel="stylesheet" type="text/css" href="{% static 'Alexandra/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'Alexandra/style.css' %}" />
        <link href="{% static 'Alexandra/blog.css' %}" rel="stylesheet">
    </head>
    
    <body>
        <!-- NAVBAR -->
        <nav class="blog-masthead navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'index' %}">Alexandra</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Dashboard</a></li>
                        <li><a href="#">Settings</a></li>
                        <li><a href="#">Profile</a></li>
                        <li><a href="#">Help</a></li>
                    </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="Search...">
                </form>
                </div>
            </div>
        </nav>
        <!-- /NAVBAR -->
        <!-- SIDEBAR -->
        <div class="container-fluid">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
                    <li><a href="{% url 'new_post' %}">New Post</a></li>
                    <li><a href="#">Lorem</a></li>
                    <li><a href="#">Ipsum</a></li>
                    <li><a href="#">Dolor</a></li>
                </ul>
                <ul class="nav nav-sidebar">
                    <li><a href="">Sit</a></li>
                    <li><a href="">Amet</a></li>
                </ul>
            </div>
            <!-- /SIDEBAR -->
            <!-- CONTENT -->
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <div class="table">
                    {% if latest_posts %}
                    <td>
                        {% for post in latest_posts %}
                        <article class="all_posts" onclick="window.location.href = '/Alexandra/post/{{post.id}}'">
                        {% if post.image_key %}
                        <img src='{{post.image_key}}' alt='user image'/>
                        {% endif %}
                        {% if post.text_content %}
                        <p>{{post.text_content}}</p>
                        {% endif %}
                        </article>
                        {% endfor %}
                    </td>
                    {% else %}
                    <p>No posts are available.</p>
                    {% endif %}
                </div>
            </div>
            <!-- /CONTENT -->
        </div>
    
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'Alexandra/enscroll-0.4.2.min.js' %}"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('.container-fluid').enscroll({
                    $(".container-fluid").height($(document).height());
                    horizontalTrackClass: 'horizontal-track2',
                    horizontalHandleClass: 'horizontal-handle2',
                    verticalScrolling: false,
                    horizontalScrolling: true,
                    addPaddingToPane: true
                });
            });
        </script>
    
    </body>
</html>

Piper/Alexandra/templates/Alexandra/indexnew.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Alexandra's Social Network</title>
    <link rel='stylesheet' type='text/css' href="{% static 'Alexandra/jquery.fullPage.css' %}"/>
</head>

<body>
    <div id='fullpage'>
        <div class='section' id='section0'>
            {% if latest_posts %}
            {% for post in latest_posts %}
            <div class='slide'>
                <h1>{{post.text_content}}</h1>
            </div>
            {% endfor %}
            {% else %}
            <p>No posts available</p>
            {% endif %}
        </div>
    </div>

    <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'></script>
    <script type='text/javascript' src="{% static 'Alexandra/jquery.fullPage.js' %}"></script>
    <script type='text/javascript'>
        $(document).ready(function() {
            $('#fullpage').fullpage({
			    scrollingSpeed: 1000
            });
        });
    </script>
</body>
</html>

Piper/Alexandra/templates/Alexandra/new_post.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Alexandra's social network</title>
        <link rel="stylesheet" type="text/css" href="{% static 'Alexandra/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'Alexandra/style.css' %}" />
        <link href="{% static 'Alexandra/blog.css' %}" rel="stylesheet">
    </head>
    
    <body>
    <!-- NAVBAR -->
        <nav class="blog-masthead navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Alexandra</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Dashboard</a></li>
                        <li><a href="#">Settings</a></li>
                        <li><a href="#">Profile</a></li>
                        <li><a href="#">Help</a></li>
                    </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="Search...">
                </form>
                </div>
            </div>
        </nav>
        <!-- /NAVBAR -->
        <!-- SIDEBAR -->
        <div class="container-fluid">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li><a href="#">Overview</a></li>
                    <li class="active"><a href="{% url 'new_post' %}">New Post <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">Lorem</a></li>
                    <li><a href="#">Ipsum</a></li>
                    <li><a href="#">Dolor</a></li>
                </ul>
                <ul class="nav nav-sidebar">
                    <li><a href="">Sit</a></li>
                    <li><a href="">Amet</a></li>
                </ul>
            </div>
            <!-- /SIDEBAR -->
            <!-- CONTENT -->
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <div class="table">
                    <h1>New Post</h1>
                    <form id='new_post_form' method='post' enctype= "multipart/form-data" action='/new_post/'>
                        {% csrf_token %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                        {% for field in form.visible_fields %}
                            <p>{{ field.label }}</p>
                            {{ field.errors }}
                            {{ field.help_text }}
                            {{ field }}
                        {% endfor %}
                        <br/>
                        <input type='submit' name='submit' value='Upload' />
                    </form>
                </div>
            </div>
            <!-- /CONTENT -->
        </div>
    
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'Alexandra/enscroll-0.4.2.min.js' %}"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('.container-fluid').enscroll({
                    $(".container-fluid").height($(document).height());
                    horizontalTrackClass: 'horizontal-track2',
                    horizontalHandleClass: 'horizontal-handle2',
                    verticalScrolling: false,
                    horizontalScrolling: true,
                    addPaddingToPane: true
                });
            });
        </script>
    
    </body>
</html>

Piper/Alexandra/templates/Alexandra/single_post.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Alexandra's social network</title>
        <link rel="stylesheet" type="text/css" href="{% static 'Alexandra/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'Alexandra/style.css' %}" />
        <link href="{% static 'Alexandra/blog.css' %}" rel="stylesheet">
    </head>
    
    <body>
    <!-- NAVBAR -->
        <nav class="blog-masthead navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Alexandra</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Dashboard</a></li>
                        <li><a href="#">Settings</a></li>
                        <li><a href="#">Profile</a></li>
                        <li><a href="#">Help</a></li>
                    </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="Search...">
                </form>
                </div>
            </div>
        </nav>
        <!-- /NAVBAR -->
        <!-- SIDEBAR -->
        <div class="container-fluid">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li><a href="#">Overview</span></a></li>
                    <li><a href="{% url 'new_post' %}">New Post</a></li>
                    <li><a href="#">Lorem</a></li>
                    <li><a href="#">Ipsum</a></li>
                    <li><a href="#">Dolor</a></li>
                </ul>
                <ul class="nav nav-sidebar">
                    <li><a href="">Sit</a></li>
                    <li><a href="">Amet</a></li>
                </ul>
            </div>
            <!-- /SIDEBAR -->
            <!-- CONTENT -->
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <div class="table">
                    {% if post.image %}
                    <article class="single_post">
                    {% if post.image %}
                    <img src="{{ post.image.url }}" alt='user image'/>
                    {% endif %}
                    {% if post.text_content %}
                    <p>{{post.text_content}}</p>
                    {% endif %}
                    </article>
                {% endif %}
                </div>
            </div>
            <!-- /CONTENT -->
        </div>
    
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'Alexandra/enscroll-0.4.2.min.js' %}"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('.container-fluid').enscroll({
                    $(".container-fluid").height($(document).height());
                    horizontalTrackClass: 'horizontal-track2',
                    horizontalHandleClass: 'horizontal-handle2',
                    verticalScrolling: false,
                    horizontalScrolling: true,
                    addPaddingToPane: true
                });
            });
        </script>
    
    </body>
</html>